import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {supabase} from './supabase';
import './style.css';

const plans={Monday:['Wake + water','Pre-workout banana','15-min easy run','Push-ups 3×8–12','DB floor press 3×12–15','DB triceps extension 3×12–15','Plank 3×30–45 sec','Cool down','High-calorie breakfast','Sleep 8:30–9:00 PM'],Tuesday:['Wake + water','Pre-workout banana','15-min easy run','Squats 4×15','DB goblet squat 3×12','Reverse lunges 3×10/leg','DB Romanian deadlift 3×15','Calf raises 4×20','Cool down','High-calorie breakfast','Sleep 8:30–9:00 PM'],Wednesday:['Wake + water','Pre-workout banana','15-min easy run','DB bent-over row 4×12–15','One-arm DB row 3×12/side','DB reverse fly 3×12–15','DB curls 3×12–15','Hammer curls 3×12–15','Superman 3×15','Cool down','Breakfast','Sleep 8:30–9:00 PM'],Thursday:['Wake + water','Light snack','15-min very easy run','10–15 min mobility','Gentle stretching','Hydrate + recovery','Breakfast','Sleep 8:30–9:00 PM'],Friday:['Wake + water','Pre-workout banana','15-min easy run','DB shoulder press 4×12','Lateral raises 3×15','Front raises 3×12','DB curls 3×15','Overhead triceps extension 3×15','Push-ups 3 sets','Cool down','Breakfast','Sleep 8:30–9:00 PM'],Saturday:['Wake + water','Pre-workout banana','15-min easy run','Full-body circuit ×3','Cool down','Breakfast','Sleep 8:30–9:00 PM'],Sunday:['Wake','Optional light walk','10–15 min stretching','Recovery + hydration','High-calorie breakfast','Sleep 8:30–9:00 PM']};
const meals=[['4:40 AM','Pre-workout','Banana + water or 2 dates + banana'],['6:45 AM','Breakfast','Paratha + curd + banana + milk OR oats + milk + banana + peanuts'],['10:00 AM','Snack','Fruit + peanuts/roasted chana + milk/curd'],['1:30 PM','Lunch','3–4 roti + rice + dal + sabzi + curd + paneer/soy/chicken'],['4:30 PM','Snack','Banana shake + peanuts OR peanut-butter sandwich + milk'],['8:00 PM','Dinner','3–4 roti + dal + sabzi + paneer/soy/chicken'],['9:00 PM','Before bed','1 glass milk']];
const days=Object.keys(plans);
const dateKey=d=>d.toISOString().slice(0,10);
const storageTasks='lb_tasks_local',storageMeals='lb_meals_local',storageWeights='lb_weights_local';

function App(){
 const [day,setDay]=useState(new Date().toLocaleDateString('en-US',{weekday:'long'}));
 const [checked,setChecked]=useState(()=>JSON.parse(localStorage.getItem(storageTasks)||'{}'));
 const [mealChecked,setMealChecked]=useState(()=>JSON.parse(localStorage.getItem(storageMeals)||'{}'));
 const [weights,setWeights]=useState(()=>JSON.parse(localStorage.getItem(storageWeights)||'[]'));
 const [weight,setWeight]=useState(''); const [dark,setDark]=useState(false); const [user,setUser]=useState(null); const [loading,setLoading]=useState(false); const [sync,setSync]=useState('Local mode');
 const today=dateKey(new Date()), dayKey=`${today}_${day}`;
 useEffect(()=>{localStorage.setItem(storageTasks,JSON.stringify(checked))},[checked]);
 useEffect(()=>{localStorage.setItem(storageMeals,JSON.stringify(mealChecked))},[mealChecked]);
 useEffect(()=>{localStorage.setItem(storageWeights,JSON.stringify(weights))},[weights]);
 useEffect(()=>{ if(!supabase)return; let mounted=true; supabase.auth.getUser().then(({data})=>{if(mounted)setUser(data.user||null)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,session)=>{if(mounted)setUser(session?.user||null)}); return()=>{mounted=false;subscription.unsubscribe()}; },[]);
 useEffect(()=>{if(user)loadCloud(user.id)},[user]);
 const done=checked[dayKey]||[]; const mealKey=today; const mealDone=mealChecked[mealKey]||[];
 const progress=Math.round(done.length/plans[day].length*100);
 const streak=useMemo(()=>{let s=0,d=new Date();while(true){const k=dateKey(d);const complete=days.some(x=>(checked[`${k}_${x}`]||[]).length===plans[x].length);if(!complete)break;s++;d.setDate(d.getDate()-1)}return s},[checked]);
 async function loadCloud(uid){setSync('Syncing…'); const [{data:wc,error:we},{data:dc,error:de},{data:weigh,error:wge}]=await Promise.all([supabase.from('workout_completions').select('date,day,task_index').eq('user_id',uid),supabase.from('diet_completions').select('date,meal').eq('user_id',uid),supabase.from('weight_entries').select('recorded_at,weight').eq('user_id',uid).order('recorded_at',{ascending:true})]); if(we||de||wge){console.error(we||de||wge);setSync('Cloud error');return;} const t={};wc.forEach(r=>{const k=`${r.date}_${r.day}`;(t[k]??=[]).push(r.task_index)});const m={};dc.forEach(r=>{(m[r.date]??=[]).push(r.meal)});setChecked(prev=>({...prev,...t}));setMealChecked(prev=>({...prev,...m}));setWeights(weigh.map(r=>({date:r.recorded_at,weight:Number(r.weight)})));setSync('Cloud synced'); }
 async function toggle(i){const isDone=done.includes(i);const next=isDone?done.filter(v=>v!==i):[...done,i];setChecked(x=>({...x,[dayKey]:next}));if(user){setSync('Saving…');if(isDone)await supabase.from('workout_completions').delete().match({user_id:user.id,date:today,day,task_index:i});else await supabase.from('workout_completions').insert({user_id:user.id,date:today,day,task_index:i,completed:true});setSync('Cloud synced')}}
 async function toggleMeal(i){const meal=meals[i][1];const isDone=mealDone.includes(meal);const next=isDone?mealDone.filter(v=>v!==meal):[...mealDone,meal];setMealChecked(x=>({...x,[mealKey]:next}));if(user){setSync('Saving…');if(isDone)await supabase.from('diet_completions').delete().match({user_id:user.id,date:today,meal});else await supabase.from('diet_completions').insert({user_id:user.id,date:today,meal,completed:true});setSync('Cloud synced')}}
 async function addWeight(){const n=Number(weight);if(!n)return;if(user){setSync('Saving…');const {error}=await supabase.from('weight_entries').insert({user_id:user.id,weight:n,recorded_at:today});if(error){alert(error.message);setSync('Cloud error');return}}const next=[...weights,{date:today,weight:n}].sort((a,b)=>a.date.localeCompare(b.date));setWeights(next);setWeight('');setSync(user?'Cloud synced':'Local mode')}
 async function login(){if(!supabase){alert('Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel Environment Variables first.');return}const email=prompt('Enter your email for a magic login link:');if(!email)return;setLoading(true);const {error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});setLoading(false);if(error)alert(error.message);else alert('Check your email and open the login link.');}
 async function logout(){await supabase?.auth.signOut();setUser(null);setSync('Local mode')}
 return <div className={dark?'app dark':'app'}><header><div><span className="eyebrow">PERSONAL FITNESS</span><h1>Lean Bulk Dashboard</h1><p>45 kg • 5'7" • Home training • Egg-free</p></div><div className="actions"><button onClick={()=>setDark(!dark)}>◐</button>{user?<button onClick={logout}>Logout</button>:<button onClick={login}>{loading?'Sending…':'Cloud Login'}</button>}</div></header>
 <div className="sync"><span>● {sync}</span>{user&&<span>{user.email}</span>}</div>
 <div className="hero"><div><strong>🔥 {streak} day streak</strong><span>Complete a full day's workout to grow the streak.</span></div><div className="progress"><div style={{width:`${progress}%`}}></div></div><b>{progress}% today</b></div>
 <nav>{days.map(d=><button key={d} className={day===d?'active':''} onClick={()=>setDay(d)}>{d.slice(0,3)}</button>)}</nav>
 <main><section><div className="card"><div className="title"><h2>{day} workout</h2><span>{done.length}/{plans[day].length}</span></div>{plans[day].map((t,i)=><label key={i} className={done.includes(i)?'task done':'task'}><input type="checkbox" checked={done.includes(i)} onChange={()=>toggle(i)}/><span>{t}</span></label>)}</div>
 <div className="card"><h2>🍛 Diet checklist</h2>{meals.map(([time,name,text],i)=><label key={name} className={mealDone.includes(name)?'meal checked':'meal'}><input type="checkbox" checked={mealDone.includes(name)} onChange={()=>toggleMeal(i)}/><span><b>{time} · {name}</b><small>{text}</small></span></label>)}<small>Eggs excluded. Keep the run easy/moderate and prioritize strength, food and recovery.</small></div></section>
 <aside><div className="card"><h2>⚖️ Weight tracker</h2><div className="weightadd"><input value={weight} onChange={e=>setWeight(e.target.value)} placeholder="kg" type="number" step="0.1"/><button onClick={addWeight}>Add</button></div>{weights.length?<div className="weights">{weights.slice(-7).reverse().map((w,i)=><div key={i}><span>{w.date}</span><b>{w.weight} kg</b></div>)}</div>:<small>No entries yet.</small>}</div><div className="card"><h2>🎯 Targets</h2><p><b>Workout:</b> morning 4:30–7:00 AM</p><p><b>Running:</b> 15 min</p><p><b>Sleep:</b> 8:30–9:00 PM</p><p><b>Equipment:</b> pair of 3 kg dumbbells</p></div><div className="card"><h2>☁️ Cloud sync</h2><p>{user?'Your workout, diet and weight data can sync through Supabase.':'Login to sync your progress across phone and PC.'}</p><button onClick={user?logout:login}>{user?'Sign out':'Connect account'}</button></div></aside></main></div>}
createRoot(document.getElementById('root')).render(<App/>);
