import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {supabase} from './supabase';
import './style.css';

const plans={Monday:['Wake + water','Pre-workout banana','15-min easy run','Push-ups 3×8–12','DB floor press 3×12–15','DB triceps extension 3×12–15','Plank 3×30–45 sec','Cool down','High-calorie breakfast','Sleep 8:30–9:00 PM'],Tuesday:['Wake + water','Pre-workout banana','15-min easy run','Squats 4×15','DB goblet squat 3×12','Reverse lunges 3×10/leg','DB Romanian deadlift 3×15','Calf raises 4×20','Cool down','High-calorie breakfast','Sleep 8:30–9:00 PM'],Wednesday:['Wake + water','Pre-workout banana','15-min easy run','DB bent-over row 4×12–15','One-arm DB row 3×12/side','DB reverse fly 3×12–15','DB curls 3×12–15','Hammer curls 3×12–15','Superman 3×15','Cool down','Breakfast','Sleep 8:30–9:00 PM'],Thursday:['Wake + water','Light snack','15-min very easy run','10–15 min mobility','Gentle stretching','Hydrate + recovery','Breakfast','Sleep 8:30–9:00 PM'],Friday:['Wake + water','Pre-workout banana','15-min easy run','DB shoulder press 4×12','Lateral raises 3×15','Front raises 3×12','DB curls 3×15','Overhead triceps extension 3×15','Push-ups 3 sets','Cool down','Breakfast','Sleep 8:30–9:00 PM'],Saturday:['Wake + water','Pre-workout banana','15-min easy run','Full-body circuit ×3','Cool down','Breakfast','Sleep 8:30–9:00 PM'],Sunday:['Wake','Optional light walk','10–15 min stretching','Recovery + hydration','High-calorie breakfast','Sleep 8:30–9:00 PM']};
const meals=[['4:40 AM','Pre-workout','Banana + water or 2 dates + banana'],['6:45 AM','Breakfast','Paratha + curd + banana + milk OR oats + milk + banana + peanuts'],['10:00 AM','Snack','Fruit + peanuts/roasted chana + milk/curd'],['1:30 PM','Lunch','3–4 roti + rice + dal + sabzi + curd + paneer/soy/chicken'],['4:30 PM','Snack','Banana shake + peanuts OR peanut-butter sandwich + milk'],['8:00 PM','Dinner','3–4 roti + dal + sabzi + paneer/soy/chicken'],['9:00 PM','Before bed','1 glass milk']];
const days=Object.keys(plans);
function dateKey(d=new Date()){return d.toISOString().slice(0,10)}
function App(){const [day,setDay]=useState(new Date().toLocaleDateString('en-US',{weekday:'long'}));const [checked,setChecked]=useState(()=>JSON.parse(localStorage.getItem('lb_tasks')||'{}'));const [weights,setWeights]=useState(()=>JSON.parse(localStorage.getItem('lb_weights')||'[]'));const [weight,setWeight]=useState('');const [dark,setDark]=useState(false);const [user,setUser]=useState(null);
useEffect(()=>{localStorage.setItem('lb_tasks',JSON.stringify(checked))},[checked]);useEffect(()=>{localStorage.setItem('lb_weights',JSON.stringify(weights))},[weights]);
useEffect(()=>{if(supabase)supabase.auth.getUser().then(({data})=>setUser(data.user||null));},[]);
const key=dateKey(), dayKey=`${key}_${day}`; const done=checked[dayKey]||[]; const progress=Math.round(done.length/plans[day].length*100);
const streak=useMemo(()=>{let s=0,d=new Date();while(true){const k=dateKey(d);const any=days.some(x=>{const a=checked[`${k}_${x}`]||[];return a.length===plans[x].length});if(!any)break;s++;d.setDate(d.getDate()-1)}return s},[checked]);
function toggle(i){setChecked(x=>({...x,[dayKey]:done.includes(i)?done.filter(v=>v!==i):[...done,i]}))}
function addWeight(){const n=Number(weight);if(!n)return;setWeights([...weights,{date:key,weight:n}].sort((a,b)=>a.date.localeCompare(b.date)));setWeight('')}
async function login(){if(!supabase)return alert('Supabase is not configured yet. Follow SETUP.md first.');const email=prompt('Email for magic-link login');if(email)await supabase.auth.signInWithOtp({email})}
return <div className={dark?'app dark':'app'}><header><div><span className="eyebrow">PERSONAL FITNESS</span><h1>Lean Bulk Dashboard</h1><p>45 kg • 5'7" • Home training • Egg-free</p></div><div className="actions"><button onClick={()=>setDark(!dark)}>◐</button><button onClick={login}>{user?'Signed in':'Cloud Login'}</button></div></header>
<div className="hero"><div><strong>🔥 {streak} day streak</strong><span>Keep your routine consistent.</span></div><div className="progress"><div style={{width:`${progress}%`}}></div></div><b>{progress}% today</b></div>
<nav>{days.map(d=><button className={day===d?'active':''} onClick={()=>setDay(d)}>{d.slice(0,3)}</button>)}</nav>
<main><section><div className="card"><div className="title"><h2>{day} workout</h2><span>{done.length}/{plans[day].length}</span></div>{plans[day].map((t,i)=><label className={done.includes(i)?'task done':'task'}><input type="checkbox" checked={done.includes(i)} onChange={()=>toggle(i)}/><span>{t}</span></label>)}</div>
<div className="card"><h2>🍛 Diet checklist</h2>{meals.map(([time,name,text])=><div className="meal"><b>{time} · {name}</b><span>{text}</span></div>)}<small>Eggs excluded. For lean bulk, keep the run easy/moderate and prioritize strength, food and recovery.</small></div></section>
<aside><div className="card"><h2>⚖️ Weight tracker</h2><div className="weightadd"><input value={weight} onChange={e=>setWeight(e.target.value)} placeholder="kg" type="number" step="0.1"/><button onClick={addWeight}>Add</button></div>{weights.length?<div className="weights">{weights.slice(-7).map(w=><div><span>{w.date}</span><b>{w.weight} kg</b></div>)}</div>:<small>No entries yet.</small>}</div><div className="card"><h2>🎯 Targets</h2><p><b>Workout:</b> morning 4:30–7:00 AM</p><p><b>Running:</b> 15 min</p><p><b>Sleep:</b> 8:30–9:00 PM</p><p><b>Equipment:</b> pair of 3 kg dumbbells</p></div></aside></main></div>}
createRoot(document.getElementById('root')).render(<App/>);
